import Link from 'next/link';
import { Reveal } from '@/components/Reveal';
import { ForgeVisual } from '@/components/ForgeVisual';
import { ForgeTimeline } from '@/components/ForgeTimeline';
export default function Home() { return <>
  <section className="hero shell"><div className="hero-copy"><p className="eyebrow"><span className="ember-dot"/> EN DIGITAL SMEDJA FÖR FÖRETAG</p><h1>Vi smider webbplatser som <em>gör intryck.</em></h1><p className="lead">Strategi, form och teknik i samma verkstad. Vi hjälper företag att synas tydligare och göra det enkelt för nästa kund att ta kontakt.</p><div className="actions"><Link href="/bestall" className="button">Beställ webbsida <span aria-hidden="true">↗</span></Link><Link href="/tjanster" className="inline-link">Utforska våra tjänster <span aria-hidden="true">↗</span></Link></div><p className="hero-note">BYGGT MED OMSORG · FÖR VERKLIGA FÖRETAG</p></div><ForgeVisual/></section>
  <div className="ticker" aria-label="Webbdesign, utveckling, sökbarhet och support"><div>WEBBDESIGN <span>✳</span> UTVECKLING <span>✳</span> SÖKBARHET <span>✳</span> SUPPORT</div></div>
  <section className="section shell"><Reveal><div className="section-head"><p className="eyebrow">VAD VI GÖR</p><h2>Rätt verktyg.<br/><em>Rätt resultat.</em></h2><p>Varje företag har sin egen riktning. Vi bygger webbplatser som ger den en tydlig form.</p></div></Reveal><div className="service-grid"><Reveal><article className="feature-card"><span className="card-icon">⌁</span><h3>Företagswebbplatser</h3><p>En snabb, tillgänglig och personlig webbplats som visar vad ni gör och varför det spelar roll.</p><Link href="/tjanster">Läs om webbplatser <span aria-hidden="true">↗</span></Link></article></Reveal><Reveal><article className="feature-card"><span className="card-icon">↗</span><h3>E-handel</h3><p>En tydlig köpupplevelse som ger era produkter den plats de förtjänar.</p><Link href="/tjanster">Läs om e-handel <span aria-hidden="true">↗</span></Link></article></Reveal><Reveal><article className="feature-card"><span className="card-icon">✳</span><h3>SEO & underhåll</h3><p>Vi hjälper er bli hittade och tar hand om webbplatsen även efter lansering.</p><Link href="/tjanster">Läs om fortsättningen <span aria-hidden="true">↗</span></Link></article></Reveal></div></section>
  <section className="section contrast-section"><div className="shell split"><Reveal><div><p className="eyebrow">VARFÖR WEBBSMEDJAN</p><h2>Digitalt hantverk,<br/><em>utan omvägar.</em></h2></div></Reveal><Reveal><div className="reasons"><div><span>01</span><div><h3>En kontakt hela vägen</h3><p>Vi håller dialogen nära och besluten begripliga från första skiss till färdig sida.</p></div></div><div><span>02</span><div><h3>Form som har en uppgift</h3><p>Designen ska hjälpa besökare att förstå er och ta nästa steg.</p></div></div><div><span>03</span><div><h3>Byggd för att hålla</h3><p>Vi prioriterar snabbhet, tillgänglighet och enkel vidareutveckling.</p></div></div></div></Reveal></div></section>
  <section className="section shell"><Reveal><div className="section-head"><p className="eyebrow">UTVALDA KONCEPT</p><h2>Idéer tar form.</h2><p>Exempel på möjliga uttryck. Koncepten är illustrationer, inte kunduppdrag.</p></div></Reveal><div className="project-grid"><div className="project-card project-a"><span className="project-label">KONCEPT / LOKALT FÖRETAG</span><strong>En tydlig plats<br/>för nästa kund.</strong></div><div className="project-card project-b"><span className="project-label">KONCEPT / E-HANDEL</span><strong>Produkter med<br/>egen karaktär.</strong></div></div><Link href="/referenser" className="inline-link project-more">Se alla koncept <span aria-hidden="true">↗</span></Link></section>
  <section className="section process-section"><div className="shell"><Reveal><p className="eyebrow">SÅ GÅR DET TILL</p><h2>Från första gnista<br/><em>till färdig webb.</em></h2></Reveal><ForgeTimeline/></div></section>
 </>; }
